<?php

namespace Openify\Bundle\ConfigurationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository
{
}
